# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PGCSVExportTool.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QRadioButton, QSizePolicy,
    QSplitter, QStatusBar, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(961, 1003)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.asetuksetFrame = QFrame(self.centralwidget)
        self.asetuksetFrame.setObjectName(u"asetuksetFrame")
        self.asetuksetFrame.setGeometry(QRect(30, 50, 591, 371))
        self.asetuksetFrame.setFrameShape(QFrame.StyledPanel)
        self.asetuksetFrame.setFrameShadow(QFrame.Raised)
        self.asetuksetFrame.setLineWidth(3)
        self.palvelinLabel = QLabel(self.asetuksetFrame)
        self.palvelinLabel.setObjectName(u"palvelinLabel")
        self.palvelinLabel.setGeometry(QRect(30, 20, 130, 20))
        font = QFont()
        font.setPointSize(14)
        self.palvelinLabel.setFont(font)
        self.porttiLabel = QLabel(self.asetuksetFrame)
        self.porttiLabel.setObjectName(u"porttiLabel")
        self.porttiLabel.setGeometry(QRect(30, 80, 130, 20))
        self.porttiLabel.setFont(font)
        self.tietokantaLabel = QLabel(self.asetuksetFrame)
        self.tietokantaLabel.setObjectName(u"tietokantaLabel")
        self.tietokantaLabel.setGeometry(QRect(30, 140, 130, 20))
        self.tietokantaLabel.setFont(font)
        self.kayttajatunnusLabel = QLabel(self.asetuksetFrame)
        self.kayttajatunnusLabel.setObjectName(u"kayttajatunnusLabel")
        self.kayttajatunnusLabel.setGeometry(QRect(30, 200, 130, 20))
        self.kayttajatunnusLabel.setFont(font)
        self.salasanaLabel = QLabel(self.asetuksetFrame)
        self.salasanaLabel.setObjectName(u"salasanaLabel")
        self.salasanaLabel.setGeometry(QRect(30, 260, 130, 20))
        self.salasanaLabel.setFont(font)
        self.yhteysPushButton = QPushButton(self.asetuksetFrame)
        self.yhteysPushButton.setObjectName(u"yhteysPushButton")
        self.yhteysPushButton.setGeometry(QRect(30, 320, 140, 30))
        self.yhteysPushButton.setFont(font)
        self.palvelinLineEdit = QLineEdit(self.asetuksetFrame)
        self.palvelinLineEdit.setObjectName(u"palvelinLineEdit")
        self.palvelinLineEdit.setGeometry(QRect(170, 20, 400, 24))
        self.palvelinLineEdit.setFont(font)
        self.porttiLineEdit = QLineEdit(self.asetuksetFrame)
        self.porttiLineEdit.setObjectName(u"porttiLineEdit")
        self.porttiLineEdit.setGeometry(QRect(170, 80, 400, 24))
        self.porttiLineEdit.setFont(font)
        self.tietokantaLineEdit = QLineEdit(self.asetuksetFrame)
        self.tietokantaLineEdit.setObjectName(u"tietokantaLineEdit")
        self.tietokantaLineEdit.setGeometry(QRect(170, 140, 400, 24))
        self.tietokantaLineEdit.setFont(font)
        self.kayttajatunnusLineEdit = QLineEdit(self.asetuksetFrame)
        self.kayttajatunnusLineEdit.setObjectName(u"kayttajatunnusLineEdit")
        self.kayttajatunnusLineEdit.setGeometry(QRect(170, 200, 400, 24))
        self.kayttajatunnusLineEdit.setFont(font)
        self.salasanaLineEdit = QLineEdit(self.asetuksetFrame)
        self.salasanaLineEdit.setObjectName(u"salasanaLineEdit")
        self.salasanaLineEdit.setGeometry(QRect(170, 260, 400, 24))
        self.salasanaLineEdit.setFont(font)
        self.erotinLabel = QLabel(self.centralwidget)
        self.erotinLabel.setObjectName(u"erotinLabel")
        self.erotinLabel.setGeometry(QRect(640, 0, 280, 30))
        font1 = QFont()
        font1.setPointSize(16)
        self.erotinLabel.setFont(font1)
        self.haePushButton = QPushButton(self.centralwidget)
        self.haePushButton.setObjectName(u"haePushButton")
        self.haePushButton.setGeometry(QRect(300, 540, 140, 30))
        self.haePushButton.setFont(font)
        self.nimiLabel = QLabel(self.centralwidget)
        self.nimiLabel.setObjectName(u"nimiLabel")
        self.nimiLabel.setGeometry(QRect(60, 440, 280, 30))
        self.nimiLabel.setFont(font1)
        self.yhteysLabel = QLabel(self.centralwidget)
        self.yhteysLabel.setObjectName(u"yhteysLabel")
        self.yhteysLabel.setGeometry(QRect(60, 0, 280, 30))
        self.yhteysLabel.setFont(font1)
        self.tyyppiComboBox = QComboBox(self.centralwidget)
        self.tyyppiComboBox.setObjectName(u"tyyppiComboBox")
        self.tyyppiComboBox.setGeometry(QRect(60, 490, 150, 27))
        self.esikatseluTableWidget = QTableWidget(self.centralwidget)
        self.esikatseluTableWidget.setObjectName(u"esikatseluTableWidget")
        self.esikatseluTableWidget.setGeometry(QRect(30, 590, 881, 371))
        self.erotinGroupBox = QGroupBox(self.centralwidget)
        self.erotinGroupBox.setObjectName(u"erotinGroupBox")
        self.erotinGroupBox.setGeometry(QRect(640, 50, 211, 251))
        self.muuLineEdit = QLineEdit(self.erotinGroupBox)
        self.muuLineEdit.setObjectName(u"muuLineEdit")
        self.muuLineEdit.setGeometry(QRect(80, 200, 110, 24))
        self.splitter = QSplitter(self.erotinGroupBox)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(20, 10, 114, 231))
        self.splitter.setOrientation(Qt.Vertical)
        self.pilkkuRadioButton = QRadioButton(self.splitter)
        self.pilkkuRadioButton.setObjectName(u"pilkkuRadioButton")
        font2 = QFont()
        font2.setPointSize(12)
        self.pilkkuRadioButton.setFont(font2)
        self.splitter.addWidget(self.pilkkuRadioButton)
        self.puolipisteRadioButton = QRadioButton(self.splitter)
        self.puolipisteRadioButton.setObjectName(u"puolipisteRadioButton")
        self.puolipisteRadioButton.setFont(font2)
        self.splitter.addWidget(self.puolipisteRadioButton)
        self.sarkainRadioButton = QRadioButton(self.splitter)
        self.sarkainRadioButton.setObjectName(u"sarkainRadioButton")
        self.sarkainRadioButton.setFont(font2)
        self.splitter.addWidget(self.sarkainRadioButton)
        self.muuRadioButton = QRadioButton(self.splitter)
        self.muuRadioButton.setObjectName(u"muuRadioButton")
        self.muuRadioButton.setFont(font2)
        self.splitter.addWidget(self.muuRadioButton)
        self.esitkatseluLabel = QLabel(self.centralwidget)
        self.esitkatseluLabel.setObjectName(u"esitkatseluLabel")
        self.esitkatseluLabel.setGeometry(QRect(60, 550, 130, 30))
        self.esitkatseluLabel.setFont(font1)
        self.nimiComboBox = QComboBox(self.centralwidget)
        self.nimiComboBox.setObjectName(u"nimiComboBox")
        self.nimiComboBox.setGeometry(QRect(300, 490, 400, 27))
        self.viePushButton = QPushButton(self.centralwidget)
        self.viePushButton.setObjectName(u"viePushButton")
        self.viePushButton.setGeometry(QRect(460, 540, 140, 30))
        self.viePushButton.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 961, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.palvelinLabel.setText(QCoreApplication.translate("MainWindow", u"Palvelin", None))
        self.porttiLabel.setText(QCoreApplication.translate("MainWindow", u"Portti", None))
        self.tietokantaLabel.setText(QCoreApplication.translate("MainWindow", u"Tietokanta", None))
        self.kayttajatunnusLabel.setText(QCoreApplication.translate("MainWindow", u"K\u00e4ytt\u00e4j\u00e4tunnus", None))
        self.salasanaLabel.setText(QCoreApplication.translate("MainWindow", u"Salasana", None))
        self.yhteysPushButton.setText(QCoreApplication.translate("MainWindow", u"Testaa yhteys", None))
        self.palvelinLineEdit.setText("")
        self.palvelinLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Palvelimen nimi tai IP-osoite", None))
        self.porttiLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"TCP-portin numero, oletus 5432", None))
        self.tietokantaLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Tietokannan nimi, hallintatieokanta postgres", None))
        self.kayttajatunnusLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"K\u00e4ytt\u00e4j\u00e4tunnus, oletusp\u00e4\u00e4k\u00e4ytt\u00e4j\u00e4 postgres", None))
        self.salasanaLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"K\u00e4ytt\u00e4j\u00e4n salasana", None))
        self.erotinLabel.setText(QCoreApplication.translate("MainWindow", u"Sarake erotin CSV tiedostossa", None))
        self.haePushButton.setText(QCoreApplication.translate("MainWindow", u"Hae", None))
        self.nimiLabel.setText(QCoreApplication.translate("MainWindow", u"Taulun tai n\u00e4kym\u00e4n nimi", None))
        self.yhteysLabel.setText(QCoreApplication.translate("MainWindow", u"Tietokantayhteyden asetukset", None))
        self.tyyppiComboBox.setCurrentText("")
        self.erotinGroupBox.setTitle("")
        self.pilkkuRadioButton.setText(QCoreApplication.translate("MainWindow", u"pilkku (,)", None))
        self.puolipisteRadioButton.setText(QCoreApplication.translate("MainWindow", u"puolipiste (;)", None))
        self.sarkainRadioButton.setText(QCoreApplication.translate("MainWindow", u"sarkain ( )", None))
        self.muuRadioButton.setText(QCoreApplication.translate("MainWindow", u"muu:", None))
        self.esitkatseluLabel.setText(QCoreApplication.translate("MainWindow", u"Esikatselu", None))
        self.viePushButton.setText(QCoreApplication.translate("MainWindow", u"Vie tiedostoon", None))
    # retranslateUi

