# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'PGViewExportTool.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QFrame,
    QGroupBox, QHeaderView, QLabel, QLineEdit,
    QPushButton, QRadioButton, QSizePolicy, QSplitter,
    QTableWidget, QTableWidgetItem, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(962, 1004)
        self.asetuksetFrame = QFrame(Dialog)
        self.asetuksetFrame.setObjectName(u"asetuksetFrame")
        self.asetuksetFrame.setGeometry(QRect(40, 70, 591, 371))
        self.asetuksetFrame.setFrameShape(QFrame.StyledPanel)
        self.asetuksetFrame.setFrameShadow(QFrame.Raised)
        self.asetuksetFrame.setLineWidth(3)
        self.palvelinLabel = QLabel(self.asetuksetFrame)
        self.palvelinLabel.setObjectName(u"palvelinLabel")
        self.palvelinLabel.setGeometry(QRect(30, 20, 130, 20))
        font = QFont()
        font.setPointSize(14)
        self.palvelinLabel.setFont(font)
        self.porttiLabel = QLabel(self.asetuksetFrame)
        self.porttiLabel.setObjectName(u"porttiLabel")
        self.porttiLabel.setGeometry(QRect(30, 80, 130, 20))
        self.porttiLabel.setFont(font)
        self.tietokantaLabel = QLabel(self.asetuksetFrame)
        self.tietokantaLabel.setObjectName(u"tietokantaLabel")
        self.tietokantaLabel.setGeometry(QRect(30, 140, 130, 20))
        self.tietokantaLabel.setFont(font)
        self.kayttajatunnusLabel = QLabel(self.asetuksetFrame)
        self.kayttajatunnusLabel.setObjectName(u"kayttajatunnusLabel")
        self.kayttajatunnusLabel.setGeometry(QRect(30, 200, 130, 20))
        self.kayttajatunnusLabel.setFont(font)
        self.salasanaLabel = QLabel(self.asetuksetFrame)
        self.salasanaLabel.setObjectName(u"salasanaLabel")
        self.salasanaLabel.setGeometry(QRect(30, 260, 130, 20))
        self.salasanaLabel.setFont(font)
        self.yhteysPushButton = QPushButton(self.asetuksetFrame)
        self.yhteysPushButton.setObjectName(u"yhteysPushButton")
        self.yhteysPushButton.setGeometry(QRect(30, 320, 140, 30))
        self.yhteysPushButton.setFont(font)
        self.palvelinLineEdit = QLineEdit(self.asetuksetFrame)
        self.palvelinLineEdit.setObjectName(u"palvelinLineEdit")
        self.palvelinLineEdit.setGeometry(QRect(170, 20, 400, 24))
        self.palvelinLineEdit.setFont(font)
        self.porttiLineEdit = QLineEdit(self.asetuksetFrame)
        self.porttiLineEdit.setObjectName(u"porttiLineEdit")
        self.porttiLineEdit.setGeometry(QRect(170, 80, 400, 24))
        self.porttiLineEdit.setFont(font)
        self.tietokantaLineEdit = QLineEdit(self.asetuksetFrame)
        self.tietokantaLineEdit.setObjectName(u"tietokantaLineEdit")
        self.tietokantaLineEdit.setGeometry(QRect(170, 140, 400, 24))
        self.tietokantaLineEdit.setFont(font)
        self.kayttajatunnusLineEdit = QLineEdit(self.asetuksetFrame)
        self.kayttajatunnusLineEdit.setObjectName(u"kayttajatunnusLineEdit")
        self.kayttajatunnusLineEdit.setGeometry(QRect(170, 200, 400, 24))
        self.kayttajatunnusLineEdit.setFont(font)
        self.salasanaLineEdit = QLineEdit(self.asetuksetFrame)
        self.salasanaLineEdit.setObjectName(u"salasanaLineEdit")
        self.salasanaLineEdit.setGeometry(QRect(170, 260, 400, 24))
        self.salasanaLineEdit.setFont(font)
        self.yhteysLabel = QLabel(Dialog)
        self.yhteysLabel.setObjectName(u"yhteysLabel")
        self.yhteysLabel.setGeometry(QRect(70, 20, 280, 30))
        font1 = QFont()
        font1.setPointSize(16)
        self.yhteysLabel.setFont(font1)
        self.esitkatseluLabel = QLabel(Dialog)
        self.esitkatseluLabel.setObjectName(u"esitkatseluLabel")
        self.esitkatseluLabel.setGeometry(QRect(70, 570, 130, 30))
        self.esitkatseluLabel.setFont(font1)
        self.esikatseluTableWidget = QTableWidget(Dialog)
        self.esikatseluTableWidget.setObjectName(u"esikatseluTableWidget")
        self.esikatseluTableWidget.setGeometry(QRect(40, 610, 881, 371))
        self.nimiLabel = QLabel(Dialog)
        self.nimiLabel.setObjectName(u"nimiLabel")
        self.nimiLabel.setGeometry(QRect(70, 460, 280, 30))
        self.nimiLabel.setFont(font1)
        self.tauluTaiNakumaComboBox = QComboBox(Dialog)
        self.tauluTaiNakumaComboBox.setObjectName(u"tauluTaiNakumaComboBox")
        self.tauluTaiNakumaComboBox.setGeometry(QRect(70, 510, 150, 27))
        self.nimiComboBox = QComboBox(Dialog)
        self.nimiComboBox.setObjectName(u"nimiComboBox")
        self.nimiComboBox.setGeometry(QRect(310, 510, 400, 27))
        self.haePushButton = QPushButton(Dialog)
        self.haePushButton.setObjectName(u"haePushButton")
        self.haePushButton.setGeometry(QRect(310, 560, 140, 30))
        self.haePushButton.setFont(font)
        self.viePushButton = QPushButton(Dialog)
        self.viePushButton.setObjectName(u"viePushButton")
        self.viePushButton.setGeometry(QRect(470, 560, 140, 30))
        self.viePushButton.setFont(font)
        self.erotinLabel = QLabel(Dialog)
        self.erotinLabel.setObjectName(u"erotinLabel")
        self.erotinLabel.setGeometry(QRect(650, 20, 280, 30))
        self.erotinLabel.setFont(font1)
        self.erotinGroupBox = QGroupBox(Dialog)
        self.erotinGroupBox.setObjectName(u"erotinGroupBox")
        self.erotinGroupBox.setGeometry(QRect(650, 70, 211, 251))
        self.muuLineEdit = QLineEdit(self.erotinGroupBox)
        self.muuLineEdit.setObjectName(u"muuLineEdit")
        self.muuLineEdit.setGeometry(QRect(80, 200, 110, 24))
        self.splitter = QSplitter(self.erotinGroupBox)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(20, 10, 114, 231))
        self.splitter.setOrientation(Qt.Vertical)
        self.pilkkuRadioButton = QRadioButton(self.splitter)
        self.pilkkuRadioButton.setObjectName(u"pilkkuRadioButton")
        font2 = QFont()
        font2.setPointSize(12)
        self.pilkkuRadioButton.setFont(font2)
        self.splitter.addWidget(self.pilkkuRadioButton)
        self.puolipisteRadioButton = QRadioButton(self.splitter)
        self.puolipisteRadioButton.setObjectName(u"puolipisteRadioButton")
        self.puolipisteRadioButton.setFont(font2)
        self.splitter.addWidget(self.puolipisteRadioButton)
        self.sarkainRadioButton = QRadioButton(self.splitter)
        self.sarkainRadioButton.setObjectName(u"sarkainRadioButton")
        self.sarkainRadioButton.setFont(font2)
        self.splitter.addWidget(self.sarkainRadioButton)
        self.muuRadioButton = QRadioButton(self.splitter)
        self.muuRadioButton.setObjectName(u"muuRadioButton")
        self.muuRadioButton.setFont(font2)
        self.splitter.addWidget(self.muuRadioButton)
        self.nimiComboBox.raise_()
        self.tauluTaiNakumaComboBox.raise_()
        self.haePushButton.raise_()
        self.viePushButton.raise_()
        self.esitkatseluLabel.raise_()
        self.nimiLabel.raise_()
        self.asetuksetFrame.raise_()
        self.yhteysLabel.raise_()
        self.esikatseluTableWidget.raise_()
        self.erotinLabel.raise_()
        self.erotinGroupBox.raise_()

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.palvelinLabel.setText(QCoreApplication.translate("Dialog", u"Palvelin", None))
        self.porttiLabel.setText(QCoreApplication.translate("Dialog", u"Portti", None))
        self.tietokantaLabel.setText(QCoreApplication.translate("Dialog", u"Tietokanta", None))
        self.kayttajatunnusLabel.setText(QCoreApplication.translate("Dialog", u"K\u00e4ytt\u00e4j\u00e4tunnus", None))
        self.salasanaLabel.setText(QCoreApplication.translate("Dialog", u"Salasana", None))
        self.yhteysPushButton.setText(QCoreApplication.translate("Dialog", u"Testaa yhteys", None))
        self.palvelinLineEdit.setText("")
        self.palvelinLineEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"Palvelimen nimi tai IP-osoite", None))
        self.porttiLineEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"TCP-portin numero, oletus 5432", None))
        self.tietokantaLineEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"Tietokannan nimi, hallintatieokanta postgres", None))
        self.kayttajatunnusLineEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"K\u00e4ytt\u00e4j\u00e4tunnus, oletusp\u00e4\u00e4k\u00e4ytt\u00e4j\u00e4 postgres", None))
        self.salasanaLineEdit.setPlaceholderText(QCoreApplication.translate("Dialog", u"K\u00e4ytt\u00e4j\u00e4n salasana", None))
        self.yhteysLabel.setText(QCoreApplication.translate("Dialog", u"Tietokantayhteyden asetukset", None))
        self.esitkatseluLabel.setText(QCoreApplication.translate("Dialog", u"Esikatselu", None))
        self.nimiLabel.setText(QCoreApplication.translate("Dialog", u"Taulun tai n\u00e4kym\u00e4n nimi", None))
        self.haePushButton.setText(QCoreApplication.translate("Dialog", u"Hae", None))
        self.viePushButton.setText(QCoreApplication.translate("Dialog", u"Vie tiedostoon", None))
        self.erotinLabel.setText(QCoreApplication.translate("Dialog", u"Sarake erotin CSV tiedostossa", None))
        self.erotinGroupBox.setTitle("")
        self.pilkkuRadioButton.setText(QCoreApplication.translate("Dialog", u"pilkku (,)", None))
        self.puolipisteRadioButton.setText(QCoreApplication.translate("Dialog", u"puolipiste (;)", None))
        self.sarkainRadioButton.setText(QCoreApplication.translate("Dialog", u"sarkain ( )", None))
        self.muuRadioButton.setText(QCoreApplication.translate("Dialog", u"muu:", None))
    # retranslateUi

